# docker-compose.yml
services:
  web:
    container_name: sfc-menu
    image: algiro/sfc-menu:latest
    ports:
      - "3000:443"
    environment:
      - NODE_ENV=production
    volumes:
      - ./nginx-certs:/etc/nginx/certs
