version: '3.8'
services:
  frontend:
    image: algiro/sfc-menu-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - VITE_SFC_MENU_ADMIN_PWD=${VITE_SFC_MENU_ADMIN_PWD:-admin123}
    networks:
      - appnet
    restart: unless-stopped

  backend:
    image: algiro/sfc-menu-backend:latest
    expose:
      - "3001"
    environment:
      - VITE_SFC_MENU_ADMIN_PWD=${VITE_SFC_MENU_ADMIN_PWD:-admin123}
    volumes:
      - ${MENU_DATA_HOST_PATH:-./data}:/app/data
    networks:
      - appnet
    restart: unless-stopped

networks:
  appnet: